[versions]
kotlin = "2.0.21"
kover = "0.9.1"
javaSource = "8"
javaTarget = "8"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
